### ISSUE TITLE
Problem with ui5-task-nwabap-deployer after ui5-task-babel

### ISSUE THREAD

**Issue by DenisTis** [pwasem/ui5-task-babel#4]
ui5-task-babel looks like cool option to make code IE11 compatible. 

However, if we integrate ui5-task-babel, ui5-task-nwabap-deployer crashes for the files, which were processed by babel.
ui5-task-babel sets different line endings, and I could not find solution to fix it :(

Seems we cannot use it in our projects at all

**Comment by pwasem** [comment]
@DenisTis 
Could you describe the exact issue in more detail?

Sounds like this could be related to `ui5-task-nwabap-deployer` itself.

I would suggest trying to use
- [@sap/abap-deploy](https://www.npmjs.com/package/@sap/abap-deploy) or
- [@sap/ux-ui5-tooling](https://www.npmjs.com/package/@sap/ux-ui5-tooling) `deploy-to-abap` task
instead.

**Comment by DenisTis** [comment]
Hi Pwasem, I will try it and let you know. If still does not work, I will prepare a better description.
Thanks for quick answer!
